source 'https://rubygems.org'

gem 'rails', '3.2.13'

gem 'sqlite3'
gem 'jquery-rails'
gem 'backbone-on-rails'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'uglifier', '>= 1.0.3'
end

group :developement do
  gem 'better_errors'
end


