source 'https://rubygems.org'

gem 'rails', '3.2.13'

gem 'sqlite3'
gem 'simple-rss'
require 'open-uri'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'debugger'
  gem 'better_errors'
end

gem 'jquery-rails'
gem 'underscore-rails'
gem 'backbone-on-rails'

# gem 'bcrypt-ruby', '~> 3.0.0'
